# Except for the secret key, none of these are actually needed; Rocket has sane
# defaults. We show all of them here explicitly for demonstrative purposes.

[global.limits]
forms = 32768
json = 1048576 # this is an extra used by the json contrib module
msgpack = 1048576 # this is an extra used by the msgpack contrib module

[development]
address = "0.0.0.0"
port = 8000
workers = 1
keep_alive = 5
log = "normal"
hi = "Hello!" # this is an unused extra; maybe application specific?
is_extra = true # this is an unused extra; maybe application specific?
secret_key = "hPRYyVRiMyxpw5sBB123241XeCMN11kFsDCqKvBi2QJx1BVHQk="

[staging]
address = "0.0.0.0"
port = 8000
workers = 2
keep_alive = 5
log = "normal"
# don't use this key! generate your own and keep it private!
secret_key = "1hPRYyVRiMyxpw5sBB123241XeCMN11kFsDCqKvBi2QJx1BVHQk1"

[production]
address = "0.0.0.0"
port = 8000
workers = 12
keep_alive = 5
log = "critical"
# don't use this key! generate your own and keep it private!
secret_key = "hPRYyVRiMyxpw5sBB123241XeCMN11kFsDCqKvBi2QJx1BVHQk1="
