[miner]
nickname = "the_name_of_miner"
region = "the_regin_of_miner"
url = "http://localhost"
capacity = 1024000000
unit_price = 100
public_key = "a406387f48914869d7b2b8fa2aedae497f316fb935107b00a4d9ab9fa5b7437a"
secret_seed = "5be9a5092b81bca64be81d212e7f2f9eba183bb7a90954f7b76361f6edb5c0a"
income_address = "5FmmZKyxXazUMmB6L8MNt2xVT87SwfRhXwFH6YtfwdR17Sb4"

[chain]
url = "ws://localhost:9944"

[data]
db = "db"
keystore = "keystore"

[search]
url = "https://www.ipse.io/v3/machine/ipse/"


[ipfs]
uri = "http://127.0.0.1:5001"
local = false